
spring:
  ai:
    chat:
      client:
        # 核心：关闭默认的单例 ChatClient 自动构建
        enabled: false
    google:
      genai:
        api-key: AIzaSyDGdXgfICtFtelVFTY-MZzQEQGOnNIx7Qs
        chat:
          options:
            model: gemini-2.5-flash
    zhipuai:
      api-key: 35065ea622b346638000955e6dd1687c.dwJoP6AqQGaS3y44
      chat:
        options:
          model: glm-4
  datasource:
    url: jdbc:mysql://117.72.145.119:3306/ai-center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: h1.c0000
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
